-- =====================================================================
-- Demo store catalog.
-- This stands in for the store's *existing* schema. The search layer
-- (next migration) only reads these tables and attaches triggers; it
-- never adds columns to them.
-- =====================================================================

create table public.brands (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  slug        text not null unique,
  description text
);

create table public.categories (
  id        bigint generated by default as identity primary key,
  name      text not null,
  slug      text not null unique,
  parent_id bigint references public.categories (id)
);

create table public.products (
  id           bigint generated by default as identity primary key,
  name         text not null,
  slug         text not null unique,
  description  text,
  brand_id     bigint references public.brands (id),
  category_id  bigint references public.categories (id),
  gender       text check (gender in ('men', 'women', 'kids', 'unisex')),
  price        numeric(10, 2) not null check (price >= 0),
  mrp          numeric(10, 2),
  rating       numeric(2, 1),
  rating_count integer not null default 0,
  popularity   integer not null default 0,   -- e.g. orders in last 90 days
  image_url    text,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table public.product_variants (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  sku        text not null unique,
  color      text,
  size       text,
  stock      integer not null default 0
);

-- Free-form attributes: material, occasion, pattern, fit, ...
create table public.product_attributes (
  product_id bigint not null references public.products (id) on delete cascade,
  name       text not null,
  value      text not null,
  primary key (product_id, name, value)
);

create index products_brand_idx     on public.products (brand_id);
create index products_category_idx  on public.products (category_id);
create index products_price_idx     on public.products (price);
create index categories_parent_idx  on public.categories (parent_id);
create index variants_product_idx   on public.product_variants (product_id);

-- Storefront data is public read-only.
alter table public.brands             enable row level security;
alter table public.categories         enable row level security;
alter table public.products           enable row level security;
alter table public.product_variants   enable row level security;
alter table public.product_attributes enable row level security;

create policy "public read" on public.brands             for select to anon, authenticated using (true);
create policy "public read" on public.categories         for select to anon, authenticated using (true);
create policy "public read" on public.products           for select to anon, authenticated using (is_active);
create policy "public read" on public.product_variants   for select to anon, authenticated using (true);
create policy "public read" on public.product_attributes for select to anon, authenticated using (true);
